### PR TITLE
use branch_protection v4

### PR DESCRIPTION
**Pull request by iAmoric**
Part of PCI-2885

### CODE REVIEW

**Comment by aliculPix4D** [comment]
Tests are failing... Can you check?

**Comment by iAmoric** [comment]
It seems test data still uses branch protection v3. I'll check

**Comment by Esysc** [comment]
> It seems test data still uses branch protection v3. I'll check

Lucas, could you keep branch protection v3? In my opinion there is no reason to get rid of it.

**Comment by odormond** [comment]
> > It seems test data still uses branch protection v3. I'll check
> 
> Lucas, could you keep branch protection v3? In my opinion there is no reason to get rid of it.

Indeed. Note that terravalet is a public repository. The tool is useable by anyone and so there is no reason to remove the support for the branch protection v3 resource.

**Comment by iAmoric** [comment]
Yes. I initially thought the goal was to replace branch protection v3 with v4. 
I fixed it, now there is both v4 and v3

**Review by aliculPix4D — APPROVED** [review]

**Review by Esysc — APPROVED** [review]

**Review by marco-m-pix4d — APPROVED** [review]

**Comment by marco-m-pix4d** [comment]
@iAmoric Do we need to update the README in a way that both people using branch protection v3 and v4 understand what they have to do (if anything) ?

**Comment by iAmoric** [comment]
@marco-m-pix4d No I think there is no need to update the README. This change just adds a new resource in the definition file. And as written in the README `Terravalet doesn't know anything about resources`

**Pull request merged**
